// lib/react/use-data.tsx
import type { Store } from "@core/store/store";
import { useEffect, useState } from "react";

export function useData<TValue extends object>(store: Store<TValue>) {
	const [isLoading, setIsLoading] = useState(true);
	const [data, setData] = useState<{ key: string; value: TValue }[]>([]);

	useEffect(() => {
		setData(store.values());

		const dispose = store.on("change", async () => {
			setData(store.values());
		});

		setIsLoading(false);

		return () => {
			setIsLoading(true);
			dispose();
		};
	}, [store]);

	return { data, isLoading };
}

// lib/solid/use-data.tsx
import { createResource, onCleanup } from "solid-js";
import type { Store } from "../core";

export function useData<T extends object>(store: Store<T>) {
	const [data, { refetch }] = createResource(store.values, {
		initialValue: [],
	});

	const unwatch = store.on("change", () => {
		refetch();
	});

	onCleanup(() => {
		unwatch();
	});

	return data;
}
