// lib/solid/use-query.tsx
import { createQuery, type Store } from "@byearlybird/starling";
import { createResource, onCleanup } from "solid-js";

export function useQuery<T extends object>(
	store: Store<T>,
	predicate: (data: T) => boolean,
) {
	const query = createQuery(store, predicate);
	const [data, { refetch, mutate }] = createResource(query.load, {
		initialValue: {},
	});

	query.on("change", (data) => {
		mutate(data);
		refetch();
	});

	onCleanup(() => {
		query.dispose();
	});

	return data;
}

// packages/starling/src/react/use-query.tsx
import { useEffect, useRef, useState } from "react";
import type { Store } from "../core";
import { createQuery } from "../core";

export function useQuery<TValue extends object>(
	store: Store<TValue>,
	predicate: (data: TValue) => boolean,
) {
	const [isLoading, setIsLoading] = useState(true);
	const [data, setData] = useState<Record<string, TValue>>({});

	const queryRef = useRef(createQuery(store, predicate));

	useEffect(() => {
		const query = queryRef.current;

		query.load().then((data) => {
			setData(data);
			setIsLoading(false);
		});

		query.on("change", (results) => {
			setData(results);
		});

		return () => {
			query.dispose();
		};
	}, []);

	return { data, isLoading };
}
